# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2938b6fe0d4767433b0bbd85ec2a448f242b8e272f9c0d273cff33d8d8850856d02cfe722fc053f68ea7d55742ce9f91fce9735667f32e4385c0b912e382bad1

test:
  secret_key_base: e43be52930e5051c286e81004d219d0951b7a4504d18b61a6961af93f06e49660a4c0aea5fdb1decf09e628ace7bce628591b09f7021b963148727216c8f2fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
